INSERT INTO items (key, name, description, weight, is_stackable, is_illegal)
VALUES
    ('scrap', 'Ferraille', 'Materiau de recuperation brut', 0.40, TRUE, FALSE),
    ('electronic_component', 'Composant electronique', 'Piece reutilisable issue de materiel technique', 0.25, TRUE, FALSE),
    ('water_bottle', 'Bouteille d''eau', 'Reserve d''eau potable standard', 0.90, TRUE, FALSE),
    ('repair_tool', 'Outil de reparation', 'Kit simple de maintenance et de recuperation.', 1.10, FALSE, FALSE)
ON CONFLICT (key) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    weight = EXCLUDED.weight,
    is_stackable = EXCLUDED.is_stackable,
    is_illegal = EXCLUDED.is_illegal,
    updated_at = NOW();

INSERT INTO gathering_nodes (
    key,
    name,
    description,
    node_type,
    result_item_key,
    min_quantity,
    max_quantity,
    required_skill_key,
    required_item_key,
    required_item_quantity,
    required_skill_level,
    stock_enabled,
    stock_quantity,
    max_stock,
    restock_seconds,
    last_restock_at,
    skill_xp,
    cooldown_seconds,
    position_x,
    position_y,
    position_z,
    radius,
    requires_proximity,
    is_active
)
VALUES
    (
        'scrap_field',
        'Champ de ferraille',
        'Zone de debris et de pieces reutilisables.',
        'scavenging',
        'scrap',
        1,
        3,
        'exploration',
        NULL,
        1,
        NULL,
        TRUE,
        25,
        25,
        1800,
        NOW(),
        8,
        300,
        NULL,
        NULL,
        NULL,
        250.0,
        FALSE,
        TRUE
    ),
    (
        'electronic_wreck',
        'Epave electronique',
        'Structure technique detruite contenant encore des composants.',
        'salvage',
        'electronic_component',
        1,
        2,
        'mechanics',
        'repair_tool',
        1,
        2,
        TRUE,
        10,
        10,
        3600,
        NOW(),
        10,
        600,
        NULL,
        NULL,
        NULL,
        250.0,
        FALSE,
        TRUE
    ),
    (
        'water_source',
        'Source d''eau',
        'Point d''approvisionnement en eau potable simple.',
        'survival',
        'water_bottle',
        1,
        2,
        NULL,
        NULL,
        1,
        NULL,
        FALSE,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        180,
        NULL,
        NULL,
        NULL,
        250.0,
        FALSE,
        TRUE
    ),
    (
        'medical_cache',
        'Cache medicale',
        'Reserve medicale de terrain encore exploitable.',
        'medical',
        'medkit_basic',
        1,
        1,
        'medicine',
        'medkit_basic',
        1,
        2,
        TRUE,
        5,
        5,
        7200,
        NOW(),
        12,
        900,
        NULL,
        NULL,
        NULL,
        250.0,
        FALSE,
        TRUE
    )
ON CONFLICT (key) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    node_type = EXCLUDED.node_type,
    result_item_key = EXCLUDED.result_item_key,
    min_quantity = EXCLUDED.min_quantity,
    max_quantity = EXCLUDED.max_quantity,
    required_skill_key = EXCLUDED.required_skill_key,
    required_item_key = EXCLUDED.required_item_key,
    required_item_quantity = EXCLUDED.required_item_quantity,
    required_skill_level = EXCLUDED.required_skill_level,
    stock_enabled = EXCLUDED.stock_enabled,
    stock_quantity = EXCLUDED.stock_quantity,
    max_stock = EXCLUDED.max_stock,
    restock_seconds = EXCLUDED.restock_seconds,
    last_restock_at = EXCLUDED.last_restock_at,
    skill_xp = EXCLUDED.skill_xp,
    cooldown_seconds = EXCLUDED.cooldown_seconds,
    position_x = EXCLUDED.position_x,
    position_y = EXCLUDED.position_y,
    position_z = EXCLUDED.position_z,
    radius = EXCLUDED.radius,
    requires_proximity = EXCLUDED.requires_proximity,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

INSERT INTO gathering_node_rewards (
    node_key,
    item_key,
    reward_type,
    min_quantity,
    max_quantity,
    chance_percent,
    is_active
)
VALUES
    ('scrap_field', 'scrap', 'primary', 1, 3, 100, TRUE),
    ('scrap_field', 'electronic_component', 'bonus', 1, 1, 20, TRUE),
    ('electronic_wreck', 'electronic_component', 'primary', 1, 2, 100, TRUE),
    ('electronic_wreck', 'scrap', 'bonus', 1, 2, 35, TRUE),
    ('water_source', 'water_bottle', 'primary', 1, 2, 100, TRUE),
    ('medical_cache', 'medkit_basic', 'primary', 1, 1, 100, TRUE)
ON CONFLICT (node_key, item_key, reward_type) DO UPDATE
SET
    min_quantity = EXCLUDED.min_quantity,
    max_quantity = EXCLUDED.max_quantity,
    chance_percent = EXCLUDED.chance_percent,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();
