CREATE TABLE IF NOT EXISTS gathering_nodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    node_type VARCHAR(100),
    result_item_key VARCHAR(100) NOT NULL,
    min_quantity INTEGER NOT NULL,
    max_quantity INTEGER NOT NULL,
    required_skill_key VARCHAR(100),
    skill_xp INTEGER NOT NULL DEFAULT 0,
    cooldown_seconds INTEGER NOT NULL,
    position_x DOUBLE PRECISION,
    position_y DOUBLE PRECISION,
    position_z DOUBLE PRECISION,
    radius DOUBLE PRECISION NOT NULL DEFAULT 250.0,
    requires_proximity BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT gathering_nodes_min_quantity_check CHECK (min_quantity > 0),
    CONSTRAINT gathering_nodes_max_quantity_check CHECK (max_quantity >= min_quantity),
    CONSTRAINT gathering_nodes_skill_xp_check CHECK (skill_xp >= 0),
    CONSTRAINT gathering_nodes_cooldown_seconds_check CHECK (cooldown_seconds > 0),
    CONSTRAINT gathering_nodes_radius_check CHECK (radius > 0)
);

CREATE INDEX IF NOT EXISTS idx_gathering_nodes_is_active
    ON gathering_nodes (is_active);

CREATE INDEX IF NOT EXISTS idx_gathering_nodes_result_item_key
    ON gathering_nodes (result_item_key);

CREATE TABLE IF NOT EXISTS character_gathering_cooldowns (
    character_id INTEGER NOT NULL,
    node_key VARCHAR(100) NOT NULL,
    last_gathered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    gather_count INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (character_id, node_key),
    CONSTRAINT character_gathering_cooldowns_character_fk
        FOREIGN KEY (character_id)
        REFERENCES characters (id)
        ON DELETE CASCADE,
    CONSTRAINT character_gathering_cooldowns_node_fk
        FOREIGN KEY (node_key)
        REFERENCES gathering_nodes (key)
        ON DELETE CASCADE,
    CONSTRAINT character_gathering_cooldowns_gather_count_check CHECK (gather_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_character_gathering_cooldowns_node_key
    ON character_gathering_cooldowns (node_key);
