CREATE TABLE IF NOT EXISTS gathering_node_rewards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_key VARCHAR(100) NOT NULL,
    item_key VARCHAR(100) NOT NULL,
    reward_type VARCHAR(20) NOT NULL,
    min_quantity INTEGER NOT NULL,
    max_quantity INTEGER NOT NULL,
    chance_percent DOUBLE PRECISION NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT gathering_node_rewards_node_key_check CHECK (BTRIM(node_key) <> ''),
    CONSTRAINT gathering_node_rewards_item_key_check CHECK (BTRIM(item_key) <> ''),
    CONSTRAINT gathering_node_rewards_type_check CHECK (reward_type IN ('primary', 'bonus')),
    CONSTRAINT gathering_node_rewards_min_quantity_check CHECK (min_quantity > 0),
    CONSTRAINT gathering_node_rewards_max_quantity_check CHECK (max_quantity >= min_quantity),
    CONSTRAINT gathering_node_rewards_chance_percent_check CHECK (chance_percent >= 0 AND chance_percent <= 100),
    CONSTRAINT gathering_node_rewards_node_fk
        FOREIGN KEY (node_key)
        REFERENCES gathering_nodes (key)
        ON DELETE CASCADE,
    CONSTRAINT gathering_node_rewards_item_fk
        FOREIGN KEY (item_key)
        REFERENCES items (key)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_gathering_node_rewards_unique_reward
    ON gathering_node_rewards (node_key, item_key, reward_type);

CREATE INDEX IF NOT EXISTS idx_gathering_node_rewards_node_key
    ON gathering_node_rewards (node_key);

CREATE INDEX IF NOT EXISTS idx_gathering_node_rewards_item_key
    ON gathering_node_rewards (item_key);

CREATE INDEX IF NOT EXISTS idx_gathering_node_rewards_is_active
    ON gathering_node_rewards (is_active);
